all: \
	in-place-merge-sort \
	o-notation \

in-place-merge-sort: in-place-merge-sort.tex
	pdflatex in-place-merge-sort.tex
	# open in-place-merge-sort.pdf

in-place-merge-sort: o-notation.tex
	pdflatex o-notation.tex
	# open o-notation.pdf


clean:
	rm *.{log,aux}
